pull_request_rules:
  - name: automatic merge when CI passes and 2 reviews
    conditions:
      - base=master
      - label=ready
    actions:
      merge:
        method: squash
      delete_head_branch: {}  
